export const CREATE_BEER_SUCCESS = "CREATE_BEER_SUCCESS";
export const DELETE_BEER_SUCCESS = "DELETE_BEER_SUCCESS";
export const UPDATE_BEER_SUCCESS = "UPDATE_BEER_SUCCESS";
export const LOAD_BEERS_SUCCESS = "LOAD_BEERS_SUCCESS";

export const LOAD_BREWERIES = "LOAD_BREWERIES";
export const CREATE_BREWERY = "CREATE_BREWERY";
